# Generated by Django 4.1.1 on 2022-09-30 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_profile"),
    ]

    operations = [
        migrations.DeleteModel(name="Profile",),
    ]
