# Generated by Django 4.1.1 on 2022-09-30 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_profile_departamento_profile_facebook_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
