# Generated by Django 4.1.1 on 2022-10-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_books_editorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cantidad',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='precio',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
