# Generated by Django 4.1.1 on 2022-10-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_books_cantidad_books_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
