# Generated by Django 4.1.1 on 2022-10-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_books_cantidad_alter_books_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='intencion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
