# Generated by Django 4.1.1 on 2022-10-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0011_alter_books_intencion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books", name="reseña", field=models.TextField(default=""),
        ),
    ]
