# Generated by Django 4.1.1 on 2022-10-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_books_reseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
    ]
