# Generated by Django 4.1.1 on 2022-09-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_comentario_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='correo',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='mensaje',
            field=models.CharField(max_length=300),
        ),
    ]
