# Generated by Django 4.1.1 on 2022-09-30 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/profile/')),
                ('departamento', models.CharField(default=None, max_length=50)),
                ('poblacion', models.CharField(default=None, max_length=50)),
                ('telefono', models.CharField(default=None, max_length=10)),
                ('whatsApp', models.CharField(default=None, max_length=10)),
                ('facebook', models.URLField(blank=True, db_index=True, default=None, max_length=700, unique=True, verbose_name='Facebook')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
