# Generated by Django 4.1.1 on 2022-10-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='poblacion',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='whatsApp',
            new_name='whatsapp',
        ),
        migrations.AlterField(
            model_name='profile',
            name='descripcion',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static\\images\\default_images\\default-avatar.png', null=True, upload_to='images/profile/'),
        ),
    ]
